"""Serve the Agent-IDE UI against the real dragzero runtime (Slice 6a).

    python run_server.py                 # deterministic FakeLLM demo, paced for animation
    python run_server.py --real          # drive a local model (LM Studio / llama.cpp)
    python run_server.py --port 8000

Then open http://127.0.0.1:8000 — the UI boots, Run decomposes the tree live, and
file chips open artifacts the agents actually wrote into the sandbox.
"""
import argparse
import os
import tempfile

from dragzero import Agent, Orchestrator, Roster, FakeLLM
from dragzero.adapters.tools_fs import FsSandbox, build_fs_tools
from dragzero.server import Run, make_server

_HERE = os.path.dirname(os.path.abspath(__file__))
UI_DIR = os.path.join(_HERE, "ui")
APP_DIST = os.path.join(_HERE, "app", "dist")
TASK = "Implement an auth module (login + session) with unit tests"


def _resolve_ui_dir(explicit: str | None) -> str:
    """Serve the React Flow app build if present (prod), else the legacy ui/ (prior-art)."""
    if explicit:
        return explicit
    return APP_DIST if os.path.isdir(APP_DIST) else UI_DIR

# Acceptance spec — what CODE checks over the sandbox, keyed by agent role (+ "__root__" for the
# entry task). The model never sets these verdicts; the gate re-derives PASS/FAIL from the files
# the agents actually wrote. Change a check and the UI's verdict changes with it.
DONE_WHEN = {
    "coder": [
        {"check": "file_exists", "artifact": "tests/auth.test.ts"},
        {"check": "grep_matches", "artifact": "tests/auth.test.ts", "params": {"pattern": "signToken"}},
    ],
    "tester": [
        {"check": "grep_matches", "artifact": "report.md", "params": {"pattern": r"\d+ passed"}},
        {"check": "grep_matches", "artifact": "report.md", "params": {"pattern": "coverage"}},
    ],
    "__root__": [  # the planner/root closes only when its children settle AND the report landed
        {"check": "all_children_done"},
        {"check": "grep_matches", "artifact": "report.md", "params": {"pattern": "coverage"}},
    ],
}


def _delegate(target, subtask):
    return {"plan": {"steps": [], "next": None}, "decision": {"mode": "delegate", "target": target, "subtask": subtask}}


def _solo():
    return {"plan": {"steps": [], "next": None}, "decision": {"mode": "solo"}}


def _tool(name, **args):
    return {"action": {"type": "tool", "tool": name, "args": args}}


def _demo_responder(ctx):
    """planner → coder (reads + writes tests) → tester (writes report, leaf)."""
    role, obs = ctx["role"], ctx["observations"]
    if role == "planner":
        return _delegate("coder", "implement tokens + write the test suite")
    if role == "coder":
        if len(obs) == 0:
            return _tool("read_file", path="src/auth/tokens.ts")
        if len(obs) == 1:
            return _tool("write_file", path="tests/auth.test.ts", content="// generated by coder\nimport { signToken } from '../src/auth/tokens';\n")
        return _delegate("tester", "run the suite and report coverage")
    if role == "tester":
        if len(obs) == 0:
            return _tool("write_file", path="report.md", content="# report\n2 passed (0.41s)\ncoverage: 86%\n")
        return _solo()
    return _solo()


def _demo_builder():
    def build():
        work = tempfile.mkdtemp(prefix="dz_run_")
        sandbox = FsSandbox(work)
        sandbox.write("src/auth/tokens.ts", "export function signToken(c){ /* ... */ }\nexport function verifyToken(t){ /* ... */ }\n")
        llm = FakeLLM(_demo_responder)
        roster = Roster([
            Agent("planner", "planner", llm),
            Agent("coder", "coder", llm),
            Agent("tester", "tester", llm),
        ])
        orch = Orchestrator(roster, tools=build_fs_tools(), sandbox=sandbox)
        return orch, roster.by_role_or_id("planner"), sandbox

    return build


def _real_builder(args):
    from dragzero.adapters.llm_local import OpenAICompatLLM

    def build():
        work = tempfile.mkdtemp(prefix="dz_run_")
        sandbox = FsSandbox(work)
        roles = ["coder", "reviewer", "tester"]
        llm = OpenAICompatLLM(base_url=args.base_url, model=args.model, api_key=args.api_key, roles=roles)
        roster = Roster([Agent("planner", "planner", llm)] + [Agent(r, r, llm) for r in roles])
        orch = Orchestrator(roster, tools=build_fs_tools(), sandbox=sandbox)
        return orch, roster.by_role_or_id("planner"), sandbox

    return build


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=8000)
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--real", action="store_true", help="drive a local model instead of FakeLLM")
    ap.add_argument("--pace", type=float, default=0.35, help="seconds between events (animation pacing)")
    ap.add_argument("--base-url", default=os.environ.get("OPENAI_BASE_URL", "http://localhost:1234/v1"))
    ap.add_argument("--model", default=os.environ.get("MODEL", "local-model"))
    ap.add_argument("--api-key", default=os.environ.get("OPENAI_API_KEY", "lm-studio"))
    ap.add_argument("--ui-dir", default=None, help="static dir to serve (default: app/dist if built, else ui/)")
    args = ap.parse_args()

    # LLM factory (callable, minted per run — never shared) drives create_run() from the authoring UI.
    if args.real:
        from dragzero.adapters.llm_local import OpenAICompatLLM
        llm_provider = lambda: OpenAICompatLLM(  # noqa: E731
            base_url=args.base_url, model=args.model, api_key=args.api_key,
            roles=["planner", "coder", "reviewer", "tester", "devops"])
    else:
        llm_provider = lambda: FakeLLM(_demo_responder)  # noqa: E731

    builder = _real_builder(args) if args.real else _demo_builder()
    pace = 0.0 if args.real else args.pace
    run = Run(id="run-1", title="auth feature", task=TASK, builder=builder, pace=pace,
              done_when=DONE_WHEN, llm_provider=llm_provider)
    httpd = make_server(run, static_dir=_resolve_ui_dir(args.ui_dir), host=args.host, port=args.port,
                        llm_provider=llm_provider)
    url = f"http://{args.host}:{args.port}"
    print(f"dragzero UI server → {url}   (Ctrl-C to stop)")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nbye")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
